### ISSUE TITLE
assertion fails in Transformations.lowerUnits

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#353] opened 2018-05-31 08:45 UTC
seems related to SMTInterpol proof tracking

chc-comp/sally-chc-benchmarks/approximate_agreement/approx.5.smt2

S: examples/settings/chccomp2018/chcToBoogie_automizer.epf
T: examples/toolchains/AutomizerCHC.xml

java.lang.AssertionError
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.Transformations.lowerUnits(Transformations.java:145)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.proof.Transformations$AvailableTransformations$2.transform(Transformations.java:56)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.retrieveProof(SMTInterpol.java:1279)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getProof(SMTInterpol.java:794)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:917)
	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.managedscript.ManagedScript.getInterpolants(ManagedScript.java:197)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.NestedInterpolantsBuilder.computeCraigInterpolants(NestedInterpolantsBuilder.java:282)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.NestedInterpolantsBuilder.<init>(NestedInterpolantsBuilder.java:165)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.InterpolatingTraceCheckCraig.computeInterpolantsTree(InterpolatingTraceCheckCraig.java:271)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.InterpolatingTraceCheckCraig.computeInterpolants(InterpolatingTraceCheckCraig.java:207)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.singletracecheck.InterpolatingTraceCheckCraig.<init>(InterpolatingTraceCheckCraig.java:109)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.TraceCheckConstructor.constructCraig(TraceCheckConstructor.java:210)

**Comment by jhoenicke** [comment] 2018-06-08 04:33
Can you extract the smt2 script for the interpolation step that fails?

**Comment by danieldietsch** [comment] 2018-06-11 14:14
I extracted the script (see attachment, remove .txt extension). 
Note that you have to run SMTInterpol with ``-ea``
[approx.5_iter2_smtinterpol_lowerunits.smt2.txt](https://github.com/ultimate-pa/ultimate/files/2090301/approx.5_iter2_smtinterpol_lowerunits.smt2.txt)

**Comment by jhoenicke** [comment] 2018-06-11 18:37
Workaround: remove `equals` and `hashcode` in Clause.java.  The problem is that Clause overwrite these and clauses with different proofs can be equal.  It looks like these are only used in proof transformations, so it hopefully doesn't break anything.

In principle it is not necessary to have the different proofs for the same clause in the proof tree.  Maybe one can preprocess the proof tree and replace all proofs for the same clause by one of them.

Without hashcode(), the smt-script runs then into a different problem, though.  The reorderings from lowerunits can create intermediate clauses of the form `(or ... lit1 (not lit1) ...)`.  This breaks some assumptions in the interpolation engine.

**Comment by danieldietsch** [comment] 2018-06-12 07:58
@jhoenicke : Are you going to integrate the fix into SMTInterpol?

**Comment by jhoenicke** [comment] 2018-07-09 08:57
I think this bug is fixed now by ultimate-pa/smtinterpol@a62eabf7 and ultimate-pa/smtinterpol@0cda0cdb.
Last I checked, the file runs out of memory in the interpolator, but this may be unavoidable (interpolants are sometimes exponential in the size of the proof tree).

**Closed** 2018-07-09 09:32 UTC
Labels: SMT, bug, in progress
