### ISSUE TITLE
Error on basic Boogie file: "Function b is already defined."

### ISSUE THREAD

**Issue by liammachado** [ultimate-pa/ultimate#444] opened 2019-08-29 17:46 UTC
I'm getting a strange error when running Ultimate Automizer on a small Boogie file using the command `./Ultimate -tc config/AutomizerBpl.xml -s config/svcomp-Reach-64bit-Automizer_Default.epf -i t.bpl`. I'm running release v0.1.24 on Ubuntu 16.04. I realize that many commits have been made since this release, so please disregard this issue if it's no longer present.

The Boogie file contents are shown below:

```
function b(int) returns (int);
axiom b(0) == 0;
procedure f() {
  assert true;
}
```

The error trace is show below:
```
This is Ultimate 0.1.24-91b1670
[2019-08-29 11:38:55,042 INFO  L170        SettingsManager]: Resetting all preferences to default values...
[2019-08-29 11:38:55,043 INFO  L174        SettingsManager]: Resetting UltimateCore preferences to default values
[2019-08-29 11:38:55,055 INFO  L177        SettingsManager]: Ultimate Commandline Interface provides no preferences, ignoring...
[2019-08-29 11:38:55,055 INFO  L174        SettingsManager]: Resetting Boogie Preprocessor preferences to default values
[2019-08-29 11:38:55,057 INFO  L174        SettingsManager]: Resetting Boogie Procedure Inliner preferences to default values
[2019-08-29 11:38:55,062 INFO  L174        SettingsManager]: Resetting Abstract Interpretation preferences to default values
[2019-08-29 11:38:55,065 INFO  L174        SettingsManager]: Resetting LassoRanker preferences to default values
[2019-08-29 11:38:55,068 INFO  L174        SettingsManager]: Resetting Reaching Definitions preferences to default values
[2019-08-29 11:38:55,073 INFO  L174        SettingsManager]: Resetting SyntaxChecker preferences to default values
[2019-08-29 11:38:55,075 INFO  L177        SettingsManager]: Büchi Program Product provides no preferences, ignoring...
[2019-08-29 11:38:55,075 INFO  L174        SettingsManager]: Resetting LTL2Aut preferences to default values
[2019-08-29 11:38:55,077 INFO  L174        SettingsManager]: Resetting PEA to Boogie preferences to default values
[2019-08-29 11:38:55,079 INFO  L174        SettingsManager]: Resetting BlockEncodingV2 preferences to default values
[2019-08-29 11:38:55,082 INFO  L174        SettingsManager]: Resetting ChcToBoogie preferences to default values
[2019-08-29 11:38:55,084 INFO  L174        SettingsManager]: Resetting AutomataScriptInterpreter preferences to default values
[2019-08-29 11:38:55,086 INFO  L174        SettingsManager]: Resetting BuchiAutomizer preferences to default values
[2019-08-29 11:38:55,088 INFO  L174        SettingsManager]: Resetting CACSL2BoogieTranslator preferences to default values
[2019-08-29 11:38:55,094 INFO  L174        SettingsManager]: Resetting CodeCheck preferences to default values
[2019-08-29 11:38:55,096 INFO  L174        SettingsManager]: Resetting InvariantSynthesis preferences to default values
[2019-08-29 11:38:55,099 INFO  L174        SettingsManager]: Resetting RCFGBuilder preferences to default values
[2019-08-29 11:38:55,101 INFO  L174        SettingsManager]: Resetting TraceAbstraction preferences to default values
[2019-08-29 11:38:55,103 INFO  L177        SettingsManager]: TraceAbstractionConcurrent provides no preferences, ignoring...
[2019-08-29 11:38:55,104 INFO  L177        SettingsManager]: TraceAbstractionWithAFAs provides no preferences, ignoring...
[2019-08-29 11:38:55,104 INFO  L174        SettingsManager]: Resetting TreeAutomizer preferences to default values
[2019-08-29 11:38:55,106 INFO  L174        SettingsManager]: Resetting IcfgTransformer preferences to default values
[2019-08-29 11:38:55,108 INFO  L174        SettingsManager]: Resetting Boogie Printer preferences to default values
[2019-08-29 11:38:55,110 INFO  L174        SettingsManager]: Resetting ReqPrinter preferences to default values
[2019-08-29 11:38:55,112 INFO  L174        SettingsManager]: Resetting Witness Printer preferences to default values
[2019-08-29 11:38:55,114 INFO  L177        SettingsManager]: Boogie PL CUP Parser provides no preferences, ignoring...
[2019-08-29 11:38:55,114 INFO  L174        SettingsManager]: Resetting CDTParser preferences to default values
[2019-08-29 11:38:55,115 INFO  L177        SettingsManager]: AutomataScriptParser provides no preferences, ignoring...
[2019-08-29 11:38:55,116 INFO  L177        SettingsManager]: ReqParser provides no preferences, ignoring...
[2019-08-29 11:38:55,116 INFO  L174        SettingsManager]: Resetting SmtParser preferences to default values
[2019-08-29 11:38:55,118 INFO  L174        SettingsManager]: Resetting Witness Parser preferences to default values
[2019-08-29 11:38:55,120 INFO  L181        SettingsManager]: Finished resetting all preferences to default values...
[2019-08-29 11:38:55,120 INFO  L98         SettingsManager]: Beginning loading settings from /home/liam/uautomizer/config/svcomp-Reach-64bit-Automizer_Default.epf
[2019-08-29 11:38:55,136 INFO  L110        SettingsManager]: Loading preferences was successful
[2019-08-29 11:38:55,136 INFO  L112        SettingsManager]: Preferences different from defaults after loading the file:
[2019-08-29 11:38:55,136 INFO  L131        SettingsManager]: Preferences of Boogie Procedure Inliner differ from their defaults:
[2019-08-29 11:38:55,136 INFO  L133        SettingsManager]:  * ... calls to implemented procedures=ONLY_FOR_CONCURRENT_PROGRAMS
[2019-08-29 11:38:55,137 INFO  L131        SettingsManager]: Preferences of BlockEncodingV2 differ from their defaults:
[2019-08-29 11:38:55,137 INFO  L133        SettingsManager]:  * Create parallel compositions if possible=false
[2019-08-29 11:38:55,137 INFO  L133        SettingsManager]:  * Use SBE=true
[2019-08-29 11:38:55,137 INFO  L131        SettingsManager]: Preferences of CACSL2BoogieTranslator differ from their defaults:
[2019-08-29 11:38:55,137 INFO  L133        SettingsManager]:  * Overapproximate operations on floating types=true
[2019-08-29 11:38:55,137 INFO  L133        SettingsManager]:  * Check division by zero=IGNORE
[2019-08-29 11:38:55,137 INFO  L133        SettingsManager]:  * Pointer to allocated memory at dereference=IGNORE
[2019-08-29 11:38:55,137 INFO  L133        SettingsManager]:  * If two pointers are subtracted or compared they have the same base address=IGNORE
[2019-08-29 11:38:55,137 INFO  L133        SettingsManager]:  * Check array bounds for arrays that are off heap=IGNORE
[2019-08-29 11:38:55,138 INFO  L133        SettingsManager]:  * Check if freed pointer was valid=false
[2019-08-29 11:38:55,138 INFO  L133        SettingsManager]:  * Use constant arrays=true
[2019-08-29 11:38:55,138 INFO  L133        SettingsManager]:  * Pointer base address is valid at dereference=IGNORE
[2019-08-29 11:38:55,138 INFO  L131        SettingsManager]: Preferences of RCFGBuilder differ from their defaults:
[2019-08-29 11:38:55,138 INFO  L133        SettingsManager]:  * Size of a code block=SequenceOfStatements
[2019-08-29 11:38:55,138 INFO  L133        SettingsManager]:  * To the following directory=./dump/
[2019-08-29 11:38:55,138 INFO  L133        SettingsManager]:  * SMT solver=External_DefaultMode
[2019-08-29 11:38:55,138 INFO  L133        SettingsManager]:  * Command for external solver=z3 SMTLIB2_COMPLIANT=true -memory:2024 -smt2 -in -t:2000
[2019-08-29 11:38:55,138 INFO  L131        SettingsManager]: Preferences of TraceAbstraction differ from their defaults:
[2019-08-29 11:38:55,139 INFO  L133        SettingsManager]:  * Compute Interpolants along a Counterexample=FPandBP
[2019-08-29 11:38:55,139 INFO  L133        SettingsManager]:  * Positions where we compute the Hoare Annotation=LoopsAndPotentialCycles
[2019-08-29 11:38:55,139 INFO  L133        SettingsManager]:  * Trace refinement strategy=CAMEL
[2019-08-29 11:38:55,139 INFO  L133        SettingsManager]:  * SMT solver=External_ModelsAndUnsatCoreMode
[2019-08-29 11:38:55,139 INFO  L133        SettingsManager]:  * Command for external solver=z3 SMTLIB2_COMPLIANT=true -memory:2024 -smt2 -in
[2019-08-29 11:38:55,139 INFO  L133        SettingsManager]:  * Compute Hoare Annotation of negated interpolant automaton, abstraction and CFG=true
[2019-08-29 11:38:55,139 INFO  L133        SettingsManager]:  * To the following directory=dump/
[2019-08-29 11:38:55,155 INFO  L81    nceAwareModelManager]: Repository-Root is: /tmp
[2019-08-29 11:38:55,163 INFO  L258   ainManager$Toolchain]: [Toolchain 1]: Applicable parser(s) successfully (re)initialized
[2019-08-29 11:38:55,165 INFO  L214   ainManager$Toolchain]: [Toolchain 1]: Toolchain selected.
[2019-08-29 11:38:55,166 INFO  L271        PluginConnector]: Initializing Boogie PL CUP Parser...
[2019-08-29 11:38:55,166 INFO  L276        PluginConnector]: Boogie PL CUP Parser initialized
[2019-08-29 11:38:55,166 INFO  L418   ainManager$Toolchain]: [Toolchain 1]: Parsing single file: /home/liam/uautomizer/test.bpl
[2019-08-29 11:38:55,167 INFO  L111           BoogieParser]: Parsing: '/home/liam/uautomizer/test.bpl'
[2019-08-29 11:38:55,182 INFO  L296   ainManager$Toolchain]: ####################### [Toolchain 1] #######################
[2019-08-29 11:38:55,183 INFO  L131        ToolchainWalker]: Walking toolchain with 3 elements.
[2019-08-29 11:38:55,183 INFO  L113        PluginConnector]: ------------------------Boogie Preprocessor----------------------------
[2019-08-29 11:38:55,183 INFO  L271        PluginConnector]: Initializing Boogie Preprocessor...
[2019-08-29 11:38:55,184 INFO  L276        PluginConnector]: Boogie Preprocessor initialized
[2019-08-29 11:38:55,197 INFO  L185        PluginConnector]: Executing the observer EnsureBoogieModelObserver from plugin Boogie Preprocessor for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/1) ...
[2019-08-29 11:38:55,198 INFO  L185        PluginConnector]: Executing the observer TypeChecker from plugin Boogie Preprocessor for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/1) ...
[2019-08-29 11:38:55,201 INFO  L185        PluginConnector]: Executing the observer ConstExpander from plugin Boogie Preprocessor for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/1) ...
[2019-08-29 11:38:55,201 INFO  L185        PluginConnector]: Executing the observer StructExpander from plugin Boogie Preprocessor for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/1) ...
[2019-08-29 11:38:55,202 INFO  L185        PluginConnector]: Executing the observer UnstructureCode from plugin Boogie Preprocessor for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/1) ...
[2019-08-29 11:38:55,203 INFO  L185        PluginConnector]: Executing the observer FunctionInliner from plugin Boogie Preprocessor for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/1) ...
[2019-08-29 11:38:55,203 INFO  L185        PluginConnector]: Executing the observer BoogieSymbolTableConstructor from plugin Boogie Preprocessor for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/1) ...
[2019-08-29 11:38:55,203 INFO  L132        PluginConnector]: ------------------------ END Boogie Preprocessor----------------------------
[2019-08-29 11:38:55,204 INFO  L113        PluginConnector]: ------------------------RCFGBuilder----------------------------
[2019-08-29 11:38:55,204 INFO  L271        PluginConnector]: Initializing RCFGBuilder...
[2019-08-29 11:38:55,204 INFO  L276        PluginConnector]: RCFGBuilder initialized
[2019-08-29 11:38:55,205 INFO  L185        PluginConnector]: Executing the observer RCFGBuilderObserver from plugin RCFGBuilder for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/1) ...
No working directory specified, using /home/liam/uautomizer/z3
Starting monitored process 1 with z3 SMTLIB2_COMPLIANT=true -memory:2024 -smt2 -in -t:2000 (exit command is (exit), workingDir is null)
Waiting until toolchain timeout for monitored process 1 with z3 SMTLIB2_COMPLIANT=true -memory:2024 -smt2 -in -t:2000
[2019-08-29 11:38:55,241 INFO  L124     BoogieDeclarations]: Specification and implementation of procedure f given in one single declaration
[2019-08-29 11:38:55,241 INFO  L130     BoogieDeclarations]: Found specification of procedure f
[2019-08-29 11:38:55,242 INFO  L138     BoogieDeclarations]: Found implementation of procedure f
[2019-08-29 11:38:55,292 INFO  L272             CfgBuilder]: Using library mode
[2019-08-29 11:38:55,292 INFO  L280             CfgBuilder]: Removed 0 assue(true) statements.
[2019-08-29 11:38:55,292 INFO  L202        PluginConnector]: Adding new model test.bpl de.uni_freiburg.informatik.ultimate.plugins.generator.rcfgbuilder CFG 29.08 11:38:55 BoogieIcfgContainer
[2019-08-29 11:38:55,292 INFO  L132        PluginConnector]: ------------------------ END RCFGBuilder----------------------------
[2019-08-29 11:38:55,293 INFO  L113        PluginConnector]: ------------------------TraceAbstraction----------------------------
[2019-08-29 11:38:55,293 INFO  L271        PluginConnector]: Initializing TraceAbstraction...
[2019-08-29 11:38:55,295 INFO  L276        PluginConnector]: TraceAbstraction initialized
[2019-08-29 11:38:55,295 INFO  L185        PluginConnector]: Executing the observer TraceAbstractionObserver from plugin TraceAbstraction for "test.bpl de.uni_freiburg.informatik.ultimate.boogie.parser AST 29.08 11:38:55" (1/2) ...
[2019-08-29 11:38:55,295 INFO  L205        PluginConnector]: Invalid model from TraceAbstraction for observer de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionObserver@6032253f and model type test.bpl de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction AST 29.08 11:38:55, skipping insertion in model container
[2019-08-29 11:38:55,296 INFO  L185        PluginConnector]: Executing the observer TraceAbstractionObserver from plugin TraceAbstraction for "test.bpl de.uni_freiburg.informatik.ultimate.plugins.generator.rcfgbuilder CFG 29.08 11:38:55" (2/2) ...
[2019-08-29 11:38:55,297 INFO  L112   eAbstractionObserver]: Analyzing ICFG test.bpl
[2019-08-29 11:38:55,302 INFO  L156   ceAbstractionStarter]: Automizer settings: Hoare:true NWA Interpolation:FPandBP Determinization: PREDICATE_ABSTRACTION
[2019-08-29 11:38:55,306 INFO  L168   ceAbstractionStarter]: Appying trace abstraction to program that has 1 error locations.
[2019-08-29 11:38:55,315 INFO  L257      AbstractCegarLoop]: Starting to check reachability of 1 error locations.
[2019-08-29 11:38:55,331 INFO  L133   ementStrategyFactory]: Using default assertion order modulation
[2019-08-29 11:38:55,331 INFO  L382      AbstractCegarLoop]: Interprodecural is true
[2019-08-29 11:38:55,331 INFO  L383      AbstractCegarLoop]: Hoare is true
[2019-08-29 11:38:55,332 INFO  L384      AbstractCegarLoop]: Compute interpolants for FPandBP
[2019-08-29 11:38:55,332 INFO  L385      AbstractCegarLoop]: Backedges is STRAIGHT_LINE
[2019-08-29 11:38:55,332 INFO  L386      AbstractCegarLoop]: Determinization is PREDICATE_ABSTRACTION
[2019-08-29 11:38:55,332 INFO  L387      AbstractCegarLoop]: Difference is false
[2019-08-29 11:38:55,332 INFO  L388      AbstractCegarLoop]: Minimize is MINIMIZE_SEVPA
[2019-08-29 11:38:55,332 INFO  L393      AbstractCegarLoop]: ======== Iteration 0==of CEGAR loop == AllErrorsAtOnce========
[2019-08-29 11:38:55,339 INFO  L276                IsEmpty]: Start isEmpty. Operand 4 states.
[2019-08-29 11:38:55,343 INFO  L282                IsEmpty]: Finished isEmpty. Found accepting run of length 2
[2019-08-29 11:38:55,343 INFO  L394         BasicCegarLoop]: Found error trace
[2019-08-29 11:38:55,343 INFO  L402         BasicCegarLoop]: trace histogram [1]
[2019-08-29 11:38:55,345 INFO  L423      AbstractCegarLoop]: === Iteration 1 === [fErr0ASSERT_VIOLATIONASSERT]===
[2019-08-29 11:38:55,348 INFO  L141       PredicateUnifier]: Initialized classic predicate unifier
[2019-08-29 11:38:55,348 INFO  L82        PathProgramCache]: Analyzing trace with hash 31, now seen corresponding path program 1 times
[2019-08-29 11:38:55,349 INFO  L223   ckRefinementStrategy]: Switched to mode SMTINTERPOL_TREE_INTERPOLANTS
[2019-08-29 11:38:55,349 INFO  L69    tionRefinementEngine]: Using refinement strategy CamelRefinementStrategy
[2019-08-29 11:38:55,378 FATAL L265        ToolchainWalker]: An unrecoverable error occured during an interaction with an SMT solver:
de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: Function b is already defined.
	at de.uni_freiburg.informatik.ultimate.logic.NoopScript.declareFun(NoopScript.java:139)
	at de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.declareFun(SMTInterpol.java:1467)
	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.cfg.SmtFunctionDefinition.defineOrDeclareFunction(SmtFunctionDefinition.java:122)
	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.cfg.SmtFunctionDefinition.defineOrDeclareFunction(SmtFunctionDefinition.java:117)
	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.cfg.SmtSymbols.transferSymbols(SmtSymbols.java:132)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.MultiTrackRefinementStrategy.constructManagedScript(MultiTrackRefinementStrategy.java:419)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.MultiTrackRefinementStrategy.constructTraceCheckConstructor(MultiTrackRefinementStrategy.java:303)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.MultiTrackRefinementStrategy.getTraceCheck(MultiTrackRefinementStrategy.java:230)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.BaseRefinementStrategy.checkFeasibility(BaseRefinementStrategy.java:223)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.BaseRefinementStrategy.executeStrategy(BaseRefinementStrategy.java:197)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.tracehandling.TraceAbstractionRefinementEngine.<init>(TraceAbstractionRefinementEngine.java:70)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.BasicCegarLoop.isCounterexampleFeasible(BasicCegarLoop.java:456)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.AbstractCegarLoop.iterateInternal(AbstractCegarLoop.java:434)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.AbstractCegarLoop.iterate(AbstractCegarLoop.java:376)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.iterate(TraceAbstractionStarter.java:334)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.runCegarLoops(TraceAbstractionStarter.java:174)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.<init>(TraceAbstractionStarter.java:126)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionObserver.finish(TraceAbstractionObserver.java:123)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:232)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:226)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:142)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:104)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:316)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.run(DefaultToolchainJob.java:145)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
[2019-08-29 11:38:55,380 INFO  L168              Benchmark]: Toolchain (without parser) took 197.91 ms. Allocated memory is still 649.6 MB. Free memory was 594.5 MB in the beginning and 571.3 MB in the end (delta: 23.2 MB). Peak memory consumption was 23.2 MB. Max. memory is 11.5 GB.
[2019-08-29 11:38:55,382 INFO  L168              Benchmark]: Boogie PL CUP Parser took 0.14 ms. Allocated memory is still 649.6 MB. Free memory is still 596.0 MB. There was no memory consumed. Max. memory is 11.5 GB.
[2019-08-29 11:38:55,382 INFO  L168              Benchmark]: Boogie Preprocessor took 20.34 ms. Allocated memory is still 649.6 MB. Free memory was 594.5 MB in the beginning and 593.2 MB in the end (delta: 1.3 MB). Peak memory consumption was 1.3 MB. Max. memory is 11.5 GB.
[2019-08-29 11:38:55,383 INFO  L168              Benchmark]: RCFGBuilder took 88.52 ms. Allocated memory is still 649.6 MB. Free memory was 593.2 MB in the beginning and 579.4 MB in the end (delta: 13.8 MB). Peak memory consumption was 13.8 MB. Max. memory is 11.5 GB.
[2019-08-29 11:38:55,383 INFO  L168              Benchmark]: TraceAbstraction took 87.13 ms. Allocated memory is still 649.6 MB. Free memory was 579.4 MB in the beginning and 571.3 MB in the end (delta: 8.1 MB). Peak memory consumption was 8.1 MB. Max. memory is 11.5 GB.
[2019-08-29 11:38:55,385 INFO  L336   ainManager$Toolchain]: #######################  End [Toolchain 1] #######################
 --- Results ---
 * Results from de.uni_freiburg.informatik.ultimate.core:
  - StatisticsResult: Toolchain Benchmarks
    Benchmark results are:
 * Boogie PL CUP Parser took 0.14 ms. Allocated memory is still 649.6 MB. Free memory is still 596.0 MB. There was no memory consumed. Max. memory is 11.5 GB.
 * Boogie Preprocessor took 20.34 ms. Allocated memory is still 649.6 MB. Free memory was 594.5 MB in the beginning and 593.2 MB in the end (delta: 1.3 MB). Peak memory consumption was 1.3 MB. Max. memory is 11.5 GB.
 * RCFGBuilder took 88.52 ms. Allocated memory is still 649.6 MB. Free memory was 593.2 MB in the beginning and 579.4 MB in the end (delta: 13.8 MB). Peak memory consumption was 13.8 MB. Max. memory is 11.5 GB.
 * TraceAbstraction took 87.13 ms. Allocated memory is still 649.6 MB. Free memory was 579.4 MB in the beginning and 571.3 MB in the end (delta: 8.1 MB). Peak memory consumption was 8.1 MB. Max. memory is 11.5 GB.
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction:
  - ExceptionOrErrorResult: SMTLIBException: Function b is already defined.
    de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction: SMTLIBException: Function b is already defined.: de.uni_freiburg.informatik.ultimate.logic.NoopScript.declareFun(NoopScript.java:139)
RESULT: Ultimate could not prove your program: Toolchain returned no result.
Received shutdown request...
Ultimate:
GTK+ Version Check
```

**Comment by danieldietsch** [comment] 2019-08-29 19:57
This is -- probably -- a duplicate of #442. I will fix this issue soon.
And I can add a new release afterwards.

**Closed as completed** 2019-09-10 15:48 UTC
Labels: bug, duplicate, SMT
