### ISSUE TITLE
Bug: UnsupportedOperationException: translation of (bvneg (_ BitVec 32) (_ BitVec 32)) not yet implemented

### ISSUE THREAD

**Issue by blizzard4591** [ultimate-pa/ultimate#578] opened 2021-12-30 18:15 UTC
### Basic Info
* Version: 0.2.2-hotfix-svcomp22-839c364
* Input file: Req1_Prop1_Batch41has_floats.c, see attached ZIP
* Settings: `./Ultimate.py --spec ../../custom-benchmarks/Floats/has_floats/reach.prp --file ../../custom-benchmarks/Floats/has_floats/Req1_Prop1_Batch41has_floats.c --full-output --architecture 32bit`
* Toolchain: The toolchain file (``.xml``, provided with the ``-tc`` argument): ?
* The complete Ultimate log file: See attached ZIP

[UA_41Bug.zip](https://github.com/ultimate-pa/ultimate/files/7794105/UA_41Bug.zip)

### Description 
The log says `please contact Matthias`, so here I am ;)
Running on generated example code, got
```
java.lang.UnsupportedOperationException: translation of (bvneg (_ BitVec 32) (_ BitVec 32)) not yet implemented, please contact Matthias
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:211)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:129)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:165)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:129)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:165)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:129)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:165)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:129)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:165)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:129)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:165)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:129)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:165)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:129)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:165)
	at de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils.boogie.Term2Expression.translate(Term2Expression.java:129)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.rcfgbuilder.RCFGBacktranslator.translateExpression(RCFGBacktranslator.java:394)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.rcfgbuilder.RCFGBacktranslator.translateExpression(RCFGBacktranslator.java:1)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.services.ModelTranslationContainer.translateExpression(ModelTranslationContainer.java:106)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.services.ModelTranslationContainer.translateExpressionToString(ModelTranslationContainer.java:89)
	at de.uni_freiburg.informatik.ultimate.core.lib.results.InvariantResult.getLongDescription(InvariantResult.java:65)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.services.ResultService.reportResult(ResultService.java:86)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.CegarLoopResultReporter.reportResult(CegarLoopResultReporter.java:141)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.createInvariantResults(TraceAbstractionStarter.java:453)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.runCegarLoops(TraceAbstractionStarter.java:192)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.<init>(TraceAbstractionStarter.java:155)
	at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionObserver.finish(TraceAbstractionObserver.java:123)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:232)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:226)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:142)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:104)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:320)
	at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.run(DefaultToolchainJob.java:145)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Heizmann** [comment] 2021-12-31 02:57
Thanks! I hope I can fix the problem this year.

**Comment by Heizmann** [comment] 2022-01-09 13:27
Sorry for the delay. I fixed the bug that the tool is crashing with an UnsupportedOperationException. So, for users that only need a yes/no verification result, the problem is gone.
I could however not fix the problem for users that also need an invariant. For our verification algorithm, we translate the C program into a Boogie program. We obtain an invariant for the Boogie program but it is currently too difficult to translate all Boogie expressions back to C expression. E.g., you will see expressions like `~bvadd64(~bvneg64(x), y)` instead of `!x+y`.
I am planning to make improvements here in the future but not in the next weeks.

**Comment by danieldietsch** [comment] 2022-01-09 21:04
I would close this issue -- if invariants are necessary, please open a separate issue.

**Closed as completed by danieldietsch** 2022-01-09 21:04 UTC
Labels: bug
